title: Dhruv Kumar
description: Security Researcher
site_title: 'Dhruvtara'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Dhruv-Kumar-1
blog_url: https://www.nagekar.com
email: dhruvkumar.anu@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
